### DISCUSSION TITLE
Styling disabled dates

### DISCUSSION THREAD

**Discussion by franz-deleon** [elreco/vue-tailwind-datepicker#87] [Q&A]
I am trying to figure out a way to style disabled and enabled dates. 

Is there a way to do this without overriding the styles like i am doing below?
```css
button.vtd-datepicker-date:not([disabled]) {
    font-weight: bold;
}
button.vtd-datepicker-date[disabled] {
    color: rgb(148 163 184);
}
```
